//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string Target { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> counter { get; set; }
        public int ID { get; set; }
    }
}
